# permissions for end users to view modelboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelbox-viewer-role
rules:
- apiGroups:
  - model.github.com
  resources:
  - modelboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - model.github.com
  resources:
  - modelboxes/status
  verbs:
  - get
